hwcomposer2: set brightness when toggling screen
droidian/wlroots pull request #9
Opened 2024-05-20 15:40 UTC by erikinkinen

Some MTKs leave the panel on when turning off the screen. This means we need to manually set the brighness to zero on when turning off the screen and restore it back to its original value when turning on the screen.

2024-05-20 15:42 UTC, erikinkinen commented
Also, if you wonder, why this should be done in wlroots, it seems that some MTKs are picky about the timing too. If you take too long or do things in wrong order, you have problems.

2024-05-20 21:14 UTC, g7 requested changes
I think perhaps a better place to check for `WLR_HWC_SYSFS_BACKLIGHT` and to acquire the udev context could be the backend, rather than doing that per-output, what do you think?

Also probably this needs to be limited to the built-in output

2024-05-29 18:42 UTC, g7 requested changes
Minor thing, looks good to me otherwise. Will test on my devices as well

2024-05-29 18:42 UTC, g7 commented on backend/hwcomposer/backend.c
> +		hwc_backend->udev = udev_new();
needs to be initialized to `NULL` when the feature is disabled

2024-05-29 22:03 UTC, g7 commented
I've squashed and added a commit on top with something else I missed during the second review: `restore_brightness` wasn't initialized, the udev object reference counter wasn't being decreased on backend destroyal and errors from udev_device_*_sysattr_value weren't being checked.

It looks okay for me now, and tested fine. One remark is that at first start it will always set the display to `max_brightness`: is this expected?

2024-05-29 22:06 UTC, erikinkinen commented
> One remark is that at first start it will always set the display to `max_brightness`: is this expected?

Yes, the sysfs value seems to initialize to zero while the harware initializes to full brightness on the devices I have. This is needed to work around that problem.

2024-05-29 22:07 UTC, g7 approved these changes
All good then

2024-05-29 22:07 UTC, merged